// app\layout.tsx
import Link from 'next/link'
import '../globals.css'
import { getPages } from '@/sanity/sanity-utils'


export const metadata = {
  title: 'Мой потрясающий сайт',
  description: 'Generated by create Next+Sanity',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  // будем возвращать все наши страницы
  const pages = await getPages()


  return (
    <html lang="en">
      <body className='max-w-3xl mx-auto py-10'>
        <header className='flex items-center justify-between'>
          {/* сделаем из нашего имени лого - которое возвращает на домашнюю страницу */}
          <Link 
          href="/"
          className="bg-gradient-to-r from-orange-300 via-yellow-300 to-purple-400
        bg-clip-text text-transparent text-lg font-bold">
          Алена
          </Link>
        
        {/* тут будет карта наших страниц */}
        <div className='flex items-center gap-5 text-sm text-gray-600'>
          {pages.map((page) => (
            <Link key={page._id} 
            href={`/${page.slug}`}
            className='hover:underline'>
              {page.title}
            </Link>
          ))}
        </div>


        </header>

        <main className='py-20'>{children}</main>
        
        </body>
    </html>
  )
}
